---
title: "Cool Thing"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(DT)
library(readr)
library(data.table)
```


```{r}
beaver2 = beaver2
beaver1 = beaver1

beaverDay1 = beaver2 %>% filter(day == 307)
beaverDay2 = beaver2 %>% filter(day == 308) 
beaverDay2$time = beaverDay2$time + 2400

beaver2 = rbind(beaverDay1, beaverDay2) 
beaver2$beaver = "beaver2"

beaverDay1 = beaver1 %>% filter(day == 346)
beaverDay2 = beaver1 %>% filter(day == 347) 
beaverDay2$time = beaverDay2$time + 2400

beaver1 = rbind(beaverDay1, beaverDay2)
beaver1$beaver = "beaver1"

beavers = rbind(beaver1, beaver2)
```

Column {data-width=50}
-----------------------------------------------------------------------
```{r}
selectInput("variable", label = "Beaver_Selection", multiple = F, choices = c("beaver1", "beaver2"), selected = "beaver2")

#actionButton("execute", "Download")
```


Column {data-width=650}
-----------------------------------------------------------------------

### Beaver Temp Plot

```{r}


beaverGraph <- reactive({
# input$variable
  beaver = beavers %>% select(input$variable, time, temp)
  })
renderPlot({
  ggplot(beaverGraph()) +
    geom_point(aes(x = time, y = temp))
})


